# Generated by Django 4.2.2 on 2023-06-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_schedule_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
